#### Label_Encoding

In [8]:
from sklearn.preprocessing import LabelEncoder
colors=['red','green','blue','yellow']
label_encoder=LabelEncoder()
labels=label_encoder.fit_transform(colors)
print(labels)

[2 1 0 3]


#### One hot Encoding

In [20]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

colors=np.array(['red','green','blue','yellow']).reshape(-1,1)
one_encoder=OneHotEncoder()
encoded=one_encoder.fit_transform(colors).toarray()
print(encoded)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


#### using get_dummies()

In [23]:
import pandas as pd
df = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue']})
encoded_df = pd.get_dummies(df['Color'])

# Print encoded data
print(encoded_df)


    Blue  Green    Red
0  False  False   True
1   True  False  False
2  False   True  False
3  False  False   True
4   True  False  False
