In [109]:
import pandas as pd
import numpy as np

In [111]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [113]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [115]:
df.shape

(5572, 2)

In [117]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [119]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

#### Creating Bag of Words using CountVectorizer

In [122]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [124]:
X_train.shape

(4457,)

In [126]:
X_test.shape

(1115,)

In [128]:
X_train[:4]

1321    Just sent again. Do you scream and moan in bed...
5149                         Pls call me da. What happen.
3443    Save money on wedding lingerie at www.bridal.p...
2149                               I will once i get home
Name: Message, dtype: object

In [130]:
y_train[:8]

1321    0
5149    0
3443    1
2149    0
3668    0
2490    0
4040    0
1820    0
Name: spam, dtype: int64

In [132]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7739 sparse matrix of type '<class 'numpy.int64'>'
	with 59240 stored elements in Compressed Sparse Row format>

In [134]:
type(X_train.values)

numpy.ndarray

In [136]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [138]:
X_train_cv.toarray()[:2][0]
X_train_cv.shape

(4457, 7739)

In [ ]:
v.vocabulary_

In [156]:
X_train_np = X_train_cv.toarray()
X_train_np[0]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [158]:
np.where(X_train_np[0]!=0)

(array([ 851,  957, 1278, 2377, 3646, 3879, 4545, 5405, 5948, 6015, 7701],
       dtype=int64),)

In [142]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [144]:
X_test_cv=v.transform(X_test)

#### Train the Naive Bayes

In [147]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [149]:
X_test_cv=v.transform(X_test)

In [151]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       949
           1       0.99      0.93      0.96       166

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [168]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)